# Generated by Django 2.2 on 2019-05-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='user_table',
            name='country',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
