# Generated by Django 2.2 on 2019-04-30 23:12

from django.db import migrations, models
import things.directionOfFile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sections', models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'Russion')])),
                ('question', models.TextField(default='')),
                ('img', models.ImageField(blank=True, default='', upload_to=things.directionOfFile.images_upload)),
                ('second_part', models.TextField(blank=True, default='')),
                ('A', models.CharField(max_length=1024)),
                ('B', models.CharField(max_length=1024)),
                ('C', models.CharField(max_length=1024)),
                ('D', models.CharField(blank=True, default='', max_length=1024)),
                ('E', models.CharField(blank=True, default='', max_length=1024)),
                ('answer', models.CharField(max_length=256)),
                ('data', models.DateField(default='2018-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=70)),
                ('university', models.CharField(blank=True, max_length=256)),
                ('speciality', models.CharField(blank=True, max_length=524)),
                ('checking', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('string', models.CharField(blank=True, default='', max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('Notcorrect', models.CharField(blank=True, default='', max_length=1024)),
            ],
        ),
    ]
