# Generated by Django 2.2.5 on 2020-03-08 09:02

from django.db import migrations, models
import django.db.models.deletion
import things.directionOfFile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('sections', models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'Russion')])),
                ('question', models.TextField(default='')),
                ('img', models.ImageField(blank=True, default='', upload_to=things.directionOfFile.images_upload)),
                ('second_part', models.TextField(blank=True, default='')),
                ('A', models.CharField(max_length=1024)),
                ('B', models.CharField(max_length=1024)),
                ('C', models.CharField(max_length=1024)),
                ('D', models.CharField(blank=True, default='', max_length=1024)),
                ('E', models.CharField(blank=True, default='', max_length=1024)),
                ('answer', models.CharField(max_length=256)),
                ('data', models.DateField(default='2018-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('university', models.CharField(blank=True, max_length=256)),
                ('speciality', models.CharField(blank=True, max_length=524)),
                ('checking', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('string', models.CharField(blank=True, default='', max_length=1024)),
                ('date', models.DateField(auto_now_add=True)),
                ('Notcorrect', models.CharField(blank=True, default='', max_length=1024)),
                ('country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='things.Country')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
