# Generated by Django 2.2.5 on 2020-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_answer_option_question_student_testinfo_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_of_work',
            field=models.CharField(default='SDU', max_length=256),
            preserve_default=False,
        ),
    ]
