# Generated by Django 2.2.5 on 2020-04-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_user_is_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='description',
            field=models.TextField(default='This description of test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinfo',
            name='duration',
            field=models.PositiveSmallIntegerField(default=60),
            preserve_default=False,
        ),
    ]
