# Generated by Django 2.2.5 on 2020-04-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_auto_20200410_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test_results',
        ),
        migrations.AddField(
            model_name='testinfo',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='tests', to='things.Student'),
        ),
    ]
