# Generated by Django 3.0.5 on 2020-04-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20200410_2144'),
        ('things', '0003_auto_20200329_1544'),
    ]

    operations = [
    ]
