# Generated by Django 2.2.5 on 2020-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20200410_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='2020-04-01 00:00:00+06:00'),
            preserve_default=False,
        ),
    ]
