# Generated by Django 3.0.5 on 2020-04-17 07:58

from django.db import migrations, models
import django.utils.timezone
import things.directionOfFile


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_merge_20200417_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=things.directionOfFile.student_photo_upload),
        ),
    ]
