# Generated by Django 2.2.5 on 2020-04-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_student_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='end_time',
            field=models.TimeField(default='16:00:00+06:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinfo',
            name='start_date',
            field=models.DateField(default='2020-04-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinfo',
            name='start_time',
            field=models.TimeField(default='14:00:00+06:00'),
            preserve_default=False,
        ),
    ]
