# Generated by Django 2.2.5 on 2020-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_auto_20200417_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
