# Generated by Django 2.2.5 on 2020-04-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0010_auto_20200417_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='testinfo',
            name='end_time',
            field=models.TimeField(default='12:00:00+06:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinfo',
            name='start_date',
            field=models.DateField(default='2020-04-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testinfo',
            name='start_time',
            field=models.TimeField(default='10:00:00+06:00'),
            preserve_default=False,
        ),
    ]
