# Generated by Django 2.2.5 on 2020-04-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0011_auto_20200417_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='speciality_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='things.Speciality'),
        ),
        migrations.AlterField(
            model_name='student',
            name='speciality',
            field=models.CharField(max_length=200),
        ),
    ]
