# Generated by Django 2.2.5 on 2020-04-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0013_speciality_migration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='speciality_link',
            new_name='speciality_fk',
        ),
    ]
