# Generated by Django 2.2.5 on 2020-04-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0014_auto_20200418_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='speciality',
        ),
    ]
