# Generated by Django 2.2.5 on 2020-04-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0015_speciality_remove'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='speciality_fk',
            new_name='speciality',
        ),
    ]
