# Generated by Django 2.2.5 on 2020-04-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0016_auto_20200418_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinfo',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
