# Generated by Django 3.0.5 on 2020-04-23 11:31

from django.db import migrations, models
import django.db.models.deletion
import things.directionOfFile


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0017_testinfo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to=things.directionOfFile.photo_upload),
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to=things.directionOfFile.student_photo_upload)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Student')),
            ],
        ),
    ]
