# Generated by Django 3.0.5 on 2020-04-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0018_auto_20200423_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
