# Generated by Django 3.0.5 on 2020-04-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0020_cheatingreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheatingreport',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheating', to='things.TestInfo'),
        ),
    ]
