# Generated by Django 2.2.5 on 2020-05-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0024_auto_20200504_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinfo',
            name='students',
        ),
    ]
