# Generated by Django 3.0.5 on 2020-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0026_testinfo_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
