# Generated by Django 2.2.5 on 2020-05-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0030_remove_cheatingreport_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
