# Generated by Django 2.2.5 on 2020-05-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0031_remove_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='things.Answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Option')),
            ],
        ),
    ]
