# Generated by Django 3.0.5 on 2020-05-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0033_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='started_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
